<template>
    <div class="level-selection-container">
      <h2>Choose Explanation Level</h2>
      <p class="description">
        Select how detailed you want your document summary to be.
      </p>
      
      <div class="level-cards">
        <LevelCard 
          v-for="level in levels" 
          :key="level.id"
          :level="level"
          :isSelected="selectedLevel === level.id"
          @select="selectLevel(level.id)"
        />
      </div>
      
      <DocumentPreview 
        :fileName="fileName" 
        :textPreview="textPreview" 
      />
      
      <div class="action-buttons">
        <button class="back-button" @click="goBack">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <line x1="19" y1="12" x2="5" y2="12"></line>
            <polyline points="12 19 5 12 12 5"></polyline>
          </svg>
          Back
        </button>
        <button 
          class="generate-button" 
          :disabled="!selectedLevel || isGenerating" 
          @click="generateSummary"
        >
          <span v-if="isGenerating">
            <LoadingSpinner />
            Generating...
          </span>
          <span v-else>Generate Summary</span>
        </button>
      </div>
    </div>
  </template>
  
  <script setup lang="ts">
  import { ref, computed } from 'vue';
  import { useRouter } from 'vue-router';
  import { useDocumentStore } from '../../stores/documentStore';
  import { useSummaryStore } from '../../stores/summaryStore';
  import LoadingSpinner from '../UI/LoadingSpinner.vue';
  import LevelCard from './LevelCard.vue';
  import DocumentPreview from './DocumentPreview.vue';
  
  const router = useRouter();
  const documentStore = useDocumentStore
  const summaryStore = useSummaryStore();

const selectedLevel = ref<number | null>(null);
const isGenerating = ref(false);

const fileName = computed(() => documentStore.fileName || 'Unnamed Document');
const textPreview = computed(() => {
  const text = documentStore.documentText;
  if (!text) return 'No text extracted';
  return text.length > 100 ? text.substring(0, 100) + '...' : text;
});

const levels = [
  { id: 1, name: 'Child (5-8 years)', emoji: '👶', description: 'Simple explanations using basic vocabulary and familiar concepts.' },
  { id: 2, name: 'Teen (13-16 years)', emoji: '🧑‍🎓', description: 'More detailed explanations with some technical terms introduced.' },
  { id: 3, name: 'College Student (18-24 years)', emoji: '🎓', description: 'In-depth explanations with field-specific terminology and concepts.' },
  { id: 4, name: 'Graduate Student (25+ years)', emoji: '🔬', description: 'Advanced explanations assuming strong background knowledge.' },
  { id: 5, name: 'Expert', emoji: '🧠', description: 'Highly technical and detailed explanations for subject matter experts.' },
  { id:6, name: 'Teacher', emoji: '👨‍🏫', description: 'Detailed explanations for teachers to help students understand complex concepts.' },
];

const selectLevel = (levelId: number) => {
  selectedLevel.value = levelId;
};

const goBack = () => {
  router.push('/');
};

const generateSummary = async () => {
  if (!selectedLevel.value) return;
  
  isGenerating.value = true;
  try {
    const level = levels.find(l => l.id === selectedLevel.value);
    if (!level) throw new Error('Invalid level selected');
    
    // In a real app, this would call your backend API to generate the summary
    await new Promise(resolve => setTimeout(resolve, 3000)); // Simulating API call
    
    const summary = `This is a simulated summary for the document "${fileName.value}" at level ${level.name}. 
    In a real application, this would be generated by calling the Gemini API with the appropriate prompt for the selected level.`;
    
    summaryStore.setSummary(summary);
    summaryStore.setLevel(level);
    
    router.push('/summary');
  } catch (error) {
    console.error('Error generating summary:', error);
    alert('An error occurred while generating the summary. Please try again.');
  } finally {
    isGenerating.value = false;
  }
};
</script>

<style lang="scss" scoped>
@use "sass:color";
.level-selection-container {
  max-width: 800px;
  margin: 0 auto;
  
  h2 {
    font-size: 1.8rem;
    margin-bottom: 1rem;
  }
  
  .description {
    color: #6b7280;
    margin-bottom: 2rem;
  }
  
  .level-cards {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 1rem;
    margin-bottom: 2rem;
  }
  
  .action-buttons {
    display: flex;
    justify-content: space-between;
    margin-top: 2rem;
    
    .back-button {
      background-color: transparent;
      color: var(--primary-color);
      border: 1px solid var(--primary-color);
      display: flex;
      align-items: center;
      gap: 0.5rem;
      
      &:hover {
        background-color: rgba(79, 70, 229, 0.05);
      }
    }
    
    .generate-button {
      display: flex;
      align-items: center;
      gap: 0.5rem;
    }
  }
}
</style>